-- Oracle 19c Database Script for Raspberry Pi Control Center
-- Table: DEVICE_DAILY_STATS (每日設備統計)

CREATE TABLE DEVICE_DAILY_STATS (
    RECORD_DATE DATE NOT NULL,              -- 日期
    DEVICE_NAME VARCHAR2(50) NOT NULL,      -- 設備名稱
    IP_ADDRESS VARCHAR2(20),                -- IP地址
    SCRIPT_PATH VARCHAR2(255),              -- 執行腳本
    RUNNING_HOURS NUMBER(10, 2) DEFAULT 0,  -- 運行時數(小時)
    ONLINE_HOURS NUMBER(10, 2) DEFAULT 0,   -- 在線時數(小時)
    OFFLINE_HOURS NUMBER(10, 2) DEFAULT 0,  -- 離線時數(小時)
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 寫入時間
    CONSTRAINT PK_DEVICE_DAILY_STATS PRIMARY KEY (RECORD_DATE, DEVICE_NAME)
);

-- Add Comments for clarity
COMMENT ON TABLE DEVICE_DAILY_STATS IS 'Raspberry Pi 每日運行統計表';
COMMENT ON COLUMN DEVICE_DAILY_STATS.RECORD_DATE IS '統計日期';
COMMENT ON COLUMN DEVICE_DAILY_STATS.DEVICE_NAME IS '設備名稱';
COMMENT ON COLUMN DEVICE_DAILY_STATS.IP_ADDRESS IS 'IP地址';
COMMENT ON COLUMN DEVICE_DAILY_STATS.SCRIPT_PATH IS '執行腳本路徑';
COMMENT ON COLUMN DEVICE_DAILY_STATS.RUNNING_HOURS IS '運行時數(小時)';
COMMENT ON COLUMN DEVICE_DAILY_STATS.ONLINE_HOURS IS '在線時數(小時)';
COMMENT ON COLUMN DEVICE_DAILY_STATS.OFFLINE_HOURS IS '離線時數(小時)';
COMMENT ON COLUMN DEVICE_DAILY_STATS.CREATED_AT IS '資料寫入時間';

-- Create Index for reporting performance
CREATE INDEX IDX_DDS_DEVICE_NAME ON DEVICE_DAILY_STATS(DEVICE_NAME);